name: chitchat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  camera: ^0.11.0
  emoji_picker_flutter: ^2.2.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.1
  lottie: ^3.1.2
  otp_text_field: ^1.1.3
  path: null
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  socket_io_client: ^2.0.3+1
  video_player: ^2.8.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/